In [1]:
import pandas as pd

# DATA UNDERSTANDING

# 1. Load the dataset
df = pd.read_csv("nba.csv")

# 2. Display the first 5 rows
print("Q2: First 5 rows")
display(df.head())

# 3. Check number of rows and columns
print("Q3: Rows and columns")
print(df.shape)

# 4. List all column names
print("Q4: Column names")
print(df.columns.tolist())


# DATA CLEANING

# 5. Convert Salary to numeric (handle errors)
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

# 6. Count missing values in each column
print("Q6: Missing values")
print(df.isnull().sum())

# 7. Drop rows where Salary is missing
df = df.dropna(subset=["Salary"]).copy()

# 8. Fill missing College values with "Unknown"
df["College"] = df["College"].fillna("Unknown")


# FILTERING DATA

# 9. Players from Boston Celtics
print("Q9: Boston Celtics players")
display(df[df["Team"] == "Boston Celtics"])

# 10. Players older than 30
print("Q10: Players older than 30")
display(df[df["Age"] > 30])

# 11. Players who play PG
print("Q11: Point Guards")
display(df[df["Position"] == "PG"])

# 12. Players with Salary greater than 5,000,000
print("Q12: Salary greater than 5 million")
display(df[df["Salary"] > 5000000])


# SORTING

# 13. Sort by Salary (highest first)
print("Q13: Highest salaries first")
display(df.sort_values(by="Salary", ascending=False))

# 14. Sort by Age (youngest first)
print("Q14: Youngest players first")
display(df.sort_values(by="Age", ascending=True))


# GROUPBY OPERATIONS

# 15. Average salary per team
print("Q15: Average salary per team")
display(df.groupby("Team")["Salary"].mean())

# 16. Number of players in each team
print("Q16: Players per team")
display(df.groupby("Team")["Name"].count())

# 17. Maximum salary in each team
print("Q17: Maximum salary per team")
display(df.groupby("Team")["Salary"].max())


# AGGREGATIONS

# 18. Average age
print("Q18: Average age")
print(df["Age"].mean())

# 19. Maximum salary
print("Q19: Maximum salary")
print(df["Salary"].max())

# 20. Minimum weight
print("Q20: Minimum weight")
print(df["Weight"].min())


# COLUMN OPERATIONS

# 21. Create Age_in_5_years
df["Age_in_5_years"] = df["Age"] + 5

print("Q21: Age in 5 years")
display(df[["Name", "Age", "Age_in_5_years"]].head())

# 22. Create Salary_in_Millions
df["Salary_in_Millions"] = df["Salary"] / 1000000

print("Q22: Salary in Millions")
display(df[["Name", "Salary", "Salary_in_Millions"]].head())


# BONUS

# 23. Team with highest total salary payout
print("Q23: Team with highest total salary")
team_salary = df.groupby("Team")["Salary"].sum()
print(team_salary.idxmax())
print(team_salary.max())

# 24. Position with highest average salary
print("Q24: Position with highest average salary")
position_salary = df.groupby("Position")["Salary"].mean()
print(position_salary.idxmax())
print(position_salary.max())

Q2: First 5 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

Q3: Rows and columns
(458, 9)
Q4: Column names
['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight', 'College', 'Salary']
Q6: Missing values
Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64
Q9: Boston Celtics players

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,Unknown,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0

Q10: Players older than 30

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,Unknown,7402812.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,Unknown,947276.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

Q11: Point Guards

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
...,...,...,...,...,...,...,...,...,...
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,Unknown,3777720.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Unknown,900000.0

Q12: Salary greater than 5 million

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,Unknown,12000000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
...,...,...,...,...,...,...,...,...,...
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0

Q13: Highest salaries first

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,Unknown,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,Unknown,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,Unknown,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
...,...,...,...,...,...,...,...,...,...
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,Unknown,30888.0

Q14: Youngest players first

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
85,Kevon Looney,Golden State Warriors,36.0,SF,20.0,6-9,220.0,UCLA,1131960.0
...,...,...,...,...,...,...,...,...,...
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,Unknown,947726.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,Unknown,8500000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0

Q15: Average salary per team

Team
Atlanta Hawks             4.860197e+06
Boston Celtics            4.181505e+06
Brooklyn Nets             3.501898e+06
Charlotte Hornets         5.222728e+06
Chicago Bulls             5.785559e+06
Cleveland Cavaliers       7.642049e+06
Dallas Mavericks          4.746582e+06
Denver Nuggets            4.294424e+06
Detroit Pistons           4.477884e+06
Golden State Warriors     5.924600e+06
Houston Rockets           5.018868e+06
Indiana Pacers            4.450122e+06
Los Angeles Clippers      6.323643e+06
Los Angeles Lakers        4.784695e+06
Memphis Grizzlies         5.467920e+06
Miami Heat                6.347359e+06
Milwaukee Bucks           4.350220e+06
Minnesota Timberwolves    4.593054e+06
New Orleans Pelicans      4.355304e+06
New York Knicks           4.581494e+06
Oklahoma City Thunder     6.251020e+06
Orlando Magic             4.297248e+06
Philadelphia 76ers        2.213778e+06
Phoenix Suns              4.229676e+06
Portland Trail Blazers    3.220121e+06
Sacramento Kings          4.778911e+06
San Antonio Spurs         5.629516e+06
Toronto Raptors           4.741174e+06
Utah Jazz                 4.204006e+06
Washington Wizards        5.088576e+06
Name: Salary, dtype: float64

Q16: Players per team

Team
Atlanta Hawks             15
Boston Celtics            14
Brooklyn Nets             15
Charlotte Hornets         15
Chicago Bulls             15
Cleveland Cavaliers       14
Dallas Mavericks          15
Denver Nuggets            14
Detroit Pistons           15
Golden State Warriors     15
Houston Rockets           15
Indiana Pacers            15
Los Angeles Clippers      15
Los Angeles Lakers        15
Memphis Grizzlies         14
Miami Heat                13
Milwaukee Bucks           16
Minnesota Timberwolves    13
New Orleans Pelicans      19
New York Knicks           16
Oklahoma City Thunder     15
Orlando Magic             14
Philadelphia 76ers        14
Phoenix Suns              15
Portland Trail Blazers    15
Sacramento Kings          15
San Antonio Spurs         15
Toronto Raptors           15
Utah Jazz                 15
Washington Wizards        15
Name: Name, dtype: int64

Q17: Maximum salary per team

Team
Atlanta Hawks             18671659.0
Boston Celtics            12000000.0
Brooklyn Nets             19689000.0
Charlotte Hornets         13500000.0
Chicago Bulls             20093064.0
Cleveland Cavaliers       22970500.0
Dallas Mavericks          16407500.0
Denver Nuggets            14000000.0
Detroit Pistons           16000000.0
Golden State Warriors     15501000.0
Houston Rockets           22359364.0
Indiana Pacers            17120106.0
Los Angeles Clippers      21468695.0
Los Angeles Lakers        25000000.0
Memphis Grizzlies         19688000.0
Miami Heat                22192730.0
Milwaukee Bucks           16407500.0
Minnesota Timberwolves    12700000.0
New Orleans Pelicans      15514031.0
New York Knicks           22875000.0
Oklahoma City Thunder     20158622.0
Orlando Magic             11250000.0
Philadelphia 76ers         6500000.0
Phoenix Suns              13500000.0
Portland Trail Blazers     8042895.0
Sacramento Kings          15851950.0
San Antonio Spurs         19689000.0
Toronto Raptors           13600000.0
Utah Jazz                 15409570.0
Washington Wizards        15851950.0
Name: Salary, dtype: float64

Q18: Average age
26.919282511210763
Q19: Maximum salary
25000000.0
Q20: Minimum weight
161.0
Q21: Age in 5 years

            Name   Age  Age_in_5_years
0  Avery Bradley  25.0            30.0
1    Jae Crowder  25.0            30.0
3    R.J. Hunter  22.0            27.0
4  Jonas Jerebko  29.0            34.0
5   Amir Johnson  29.0            34.0

Q22: Salary in Millions

            Name      Salary  Salary_in_Millions
0  Avery Bradley   7730337.0            7.730337
1    Jae Crowder   6796117.0            6.796117
3    R.J. Hunter   1148640.0            1.148640
4  Jonas Jerebko   5000000.0            5.000000
5   Amir Johnson  12000000.0           12.000000

Q23: Team with highest total salary
Cleveland Cavaliers
106988689.0
Q24: Position with highest average salary
C
5967052.0